Feature/show events
makitango/curiocity pull request #5
Opened 2023-11-22 08:47 UTC by makitango

2023-11-27 15:17 UTC, makitango commented
Implemented backend, frontend and styling for showing a list of events. Also created the backend and frontend to add an event, but without testing (will be part of the AddEvent task).
Included backend testing and a small frontent test using jest.

2023-11-28 11:12 UTC, AljoschaNy requested changes
Soweit sieht es schon sehr gut aus. Ein paar Änderungen würde ich allerdings noch vornehmen

2023-11-29 07:45 UTC, AljoschaNy commented on backend/src/main/java/com/github/makitango/curiocity/event/EventController.java
> +    }
Das ist eine Möglichkeit. Es gibt allerdings auch eine Annotation @AllArgsConstructor von Spring boot, die du über deiner class hinzufügen könntest, sodass du dir die Zeilen sparen könntest.

2023-11-29 08:34 UTC, makitango commented on backend/src/main/java/com/github/makitango/curiocity/event/EventController.java
> +    }
Stimmt total. Warum hab ich lombok, wenn ich das nicht nutze. ;)

2023-11-29 09:00 UTC, AljoschaNy requested changes

2023-11-29 09:00 UTC, AljoschaNy commented on backend/src/test/java/com/github/makitango/curiocity/event/EventControllerTest.java
> +        assertEquals(List.of("Stannis Baratheon"), addedEvent.usersWhoDownvoted());
Das würde ich noch ändern, ansonsten sieht alles top aus

2023-11-29 09:17 UTC, AljoschaNy approved these changes
Lgtm, top!

2023-11-29 09:23 UTC, merged